### ISSUE TITLE
why I can't close the browser use ‘launch.close’ under the mode of 'headless'

### ISSUE THREAD

**Issue by lateautunm** [GoogleChrome/puppeteer#3448]
hi !
Recent I code with puppeteer,But I have a problem about close the  launch

the first 

when i find open more than 50 pages,the next i use goto(url), i will be so so so slow,but as long as i reopen a launch，it fast again, so i decide close the launch first,then open a new launch, but i use `launch.close()` it can close, i must add `page.close()` then execute `launch.close()` it will be normal， so  i want to ask why i can't close the launch directly

Can you answer my question?

thanks

**Comment by aslushnikov** [comment]
Hey @lateautunm,

I guess the `launch` is a `browser`? In this case, `browser.close()` should be working directly without any need for the intermediate `page.close()`. If it doesn't work for you, can you please re-file this issue with additional details:
- puppeteer version
- operating system
- (the most important) script that I can run locally and that would reproduce the problem. I don't think I can help debugging your issues without the actual code snippet.

Thanks!
